### ISSUE TITLE
How is a gpx-file or -dataset to be integrated? 

### ISSUE THREAD

**Issue by buttoni2020** [sgraaf/papermap#2]
Hey,
my aim is to visualize my track in a topo (+ some statistics) and storing everything into a picture (preferable pdf, but png or svg should work as well, not jpg).
Somehow papermap seems to be the most easiest solution. But as of today I am not captable to integrate my gpx-track into the map.

When running code in spyder (wpy64-3830) with papermap 0.2 from this git I receive an error.
zentral Error-line seems to be:

``` 
from papermap import PaperMap

 # [run calculation of center_ns and center_ew]

pm = PaperMap(center_ns, center_ew, tile_server="ESRI Dark Gray", size="A3", scale=25000, quiet=True, gpx="2020-07-22_Eiger/20200721-142919.gpx")
...
```

Error-Code:
```
pm = PaperMap(center_ns, center_ew, tile_server="ESRI Dark Gray", size="A3", scale=25000, quiet=True, gpx="2020-07-22_Eiger/20200721-142919.gpx") #gpx="2020-07-22_Eiger/20200721-142919.gpx"

  File "C:\Users\[...]\WPy64-3830\python-3.8.3.amd64\lib\site-packages\papermap\papermap.py", line 163, in __init__
    if is_out_of_bounds(self.gpx.bounds, self.bounds):

AttributeError: 'str' object has no attribute 'bounds'
```

Note: values of "center_ns"  and "center_ew" are calculated by panda out of track-file (csv).
This seems to be working - pm w/o gpx="..." provides an proper pdf-map as requested. 

Thank you very much upfront to provide this program and for any support.
Chers

**Comment by sgraaf** [comment]
Hi! Thank you for using PaperMap first and foremost 😀. The error you're getting is due to the fact that you first need to initialize a GPX-object, which you then pass as a kwarg when initializing the PaperMap:
```python
from papermap import PaperMap
from papermap.gpx import GPX

gpx = GPX("2020-07-22_Eiger/20200721-142919.gpx")
pm = PaperMap(center_ns, center_ew, tile_server="ESRI Dark Gray", size="A3", scale=25000, quiet=True, gpx=gpx)
...
```

**Comment by buttoni2020** [comment]
thank you very much for fast reply. at least no issue on these gpx-lines anymore, but might found the next one (#3 )
